version: '3'

# Define services
services:

  # App Service
  app:
    # Configuration for building the docker image for the service
    build:
      context: . # Use an image built from the specified dockerfile in the current directory.
      dockerfile: Dockerfile
    ports:
      - "3080:3080" # Forward the exposed port 8080 on the container to port 8080 on the host machine
    restart: unless-stopped    
    networks: # Networks to join (Services on the same network can communicate with each other using their name)
      - backend

  db:
    image: mysql:8.0.27
    container_name: gormDB
    restart: unless-stopped
    environment:
      MYSQL_USER: admin
      MYSQL_ROOT_PASSWORD: root
      MYSQL_PASSWORD: admin
      MYSQL_DATABASE: gorm
    ports:
    - "3377:3306"
    networks:
      - backend
  
networks:
  backend:    
    driver: bridge
